In [8]:
import numpy as np 


In [28]:
table  = np.ones((3,3))
table

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [35]:
np.arange(0,12).reshape((4,2))

ValueError: cannot reshape array of size 12 into shape (4,2)

In [41]:
np.linspace(0,12,10)

array([ 0.        ,  1.33333333,  2.66666667,  4.        ,  5.33333333,
        6.66666667,  8.        ,  9.33333333, 10.66666667, 12.        ])

In [49]:
np.random.random((3,2))*4

array([[3.45190559, 1.0202619 ],
       [2.08205958, 0.49148556],
       [3.83779656, 0.74351222]])

In [55]:
a = np.array([2,2,2])
b= np.array([[1,2,3],[2,3,4],[2,3,4]])

a.dot(b)

array([10, 16, 22])

In [56]:
a+1

array([3, 3, 3])

In [62]:
a.mean()

2.0

In [70]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
A = np.arange(10, 19).reshape((3, 3))

In [72]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [92]:
A[2:,2:]

array([[18]])

In [105]:
for row in A:
    print(row*2)

[20 22 24]
[26 28 30]
[32 34 36]


In [108]:
def recursiveStars(n):
    if( n > 10):
        return 
    
    print(n*'*')
    recursiveStars(n+1)

In [109]:
recursiveStars(5)

*****
******
*******
********
*********
**********


In [114]:
for i in A.flat : 
    print(i)

10
11
12
13
14
15
16
17
18


In [115]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [120]:
np.apply_along_axis(np.mean , axis = 1 , arr= A)

array([11., 14., 17.])

In [122]:
#Conditions and Boolean Arrays
A = np.random.random((4,4))

A

array([[0.45370532, 0.96165542, 0.5577919 , 0.04669641],
       [0.11995757, 0.11392511, 0.59374201, 0.42565685],
       [0.7447379 , 0.07676002, 0.0905394 , 0.097607  ],
       [0.96886911, 0.41087857, 0.59519388, 0.94824413]])

In [123]:
A<0.5

array([[ True, False, False,  True],
       [ True,  True, False,  True],
       [False,  True,  True,  True],
       [False,  True, False, False]])

In [124]:
A[A<0.5]

array([0.45370532, 0.04669641, 0.11995757, 0.11392511, 0.42565685,
       0.07676002, 0.0905394 , 0.097607  , 0.41087857])

In [125]:
a = np.random.random(12)
a

array([0.47169138, 0.23965294, 0.27131519, 0.82600505, 0.26639918,
       0.31305034, 0.51919807, 0.61781636, 0.96724427, 0.81705516,
       0.52598256, 0.74556074])

In [126]:
A = a.reshape(3, 4)

In [127]:
A

array([[0.47169138, 0.23965294, 0.27131519, 0.82600505],
       [0.26639918, 0.31305034, 0.51919807, 0.61781636],
       [0.96724427, 0.81705516, 0.52598256, 0.74556074]])

In [128]:
a

array([0.47169138, 0.23965294, 0.27131519, 0.82600505, 0.26639918,
       0.31305034, 0.51919807, 0.61781636, 0.96724427, 0.81705516,
       0.52598256, 0.74556074])

In [129]:
a.shape = (3,4)

In [130]:
a

array([[0.47169138, 0.23965294, 0.27131519, 0.82600505],
       [0.26639918, 0.31305034, 0.51919807, 0.61781636],
       [0.96724427, 0.81705516, 0.52598256, 0.74556074]])

In [131]:
a = a.ravel()

In [132]:
a

array([0.47169138, 0.23965294, 0.27131519, 0.82600505, 0.26639918,
       0.31305034, 0.51919807, 0.61781636, 0.96724427, 0.81705516,
       0.52598256, 0.74556074])